# Generated by Django 5.1 on 2024-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_studentmodel_delete_login_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_query', models.CharField(max_length=400)),
            ],
        ),
    ]
